job('First-Maven-Project-DSL') {
    description("My First-Maven-Project generated by the DSL on ${new Date()}, which is a small maven project")
    scm {
        github('https://github.com/Vijay2533/Jenkins_Upgradev3.git', 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package','java-tomcat-sample/pom.xml')
    }
    publishers {
        archiveArtifacts('**/*.war')
    }
}